### ISSUE TITLE
Allow page to be set to 1 on application of filter

### ISSUE THREAD

**Issue by useafterfree** [unosquare/tubular-react#1030]
**Is your feature request related to a problem? Please describe.**
When a user is paginated beyond page one, it is confusing where that any results were returned when a filter is applied

**Describe the solution you'd like**
Upon an application of the filter, the user is returned to page 1

**Additional context**

Observe no results are provided but user has to select page 1 to see results:
![image](https://user-images.githubusercontent.com/35079898/109075243-b8fde980-76ad-11eb-9c87-575271057517.png)

**Comment by kadosh** [comment]
hi @useafterfree,

the tubular core is returning to the first page behind the scenes whenever ```setColumns``` is called. So, you should not need to explicitly tell tubular to go to the first page after setting the columns.

Maybe you're experiencing a different issue. Take a look at the following gif:

![tb-filter-going-first-page](https://user-images.githubusercontent.com/399019/109254565-e20aa100-77b7-11eb-9490-b4c5e33ce529.gif)

If you can replicate the issue on codesandbox or provide more information I could take a look at it

**Comment by useafterfree** [comment]
I just realized I have to conditionally decorate the API call with `CurrentPage: 1` when a filter is applied. Thanks for the assistance!
