### ISSUE TITLE
Local Data - Optional Response Values

### ISSUE THREAD

**Issue by buda1994** [unosquare/tubular-react#167]
Right now you have to set a value in the `Response` for each one of the columns you defined, even if you don't need a value for a column in some rows

Example:
```javascript
{
  OrderID: 1,
  CustomerName: 'Microsoft',
  ShippedDate: '2016-03-19T19:00:00',
  ShipperCity: 'Guadalajara, JAL, Mexico',
  Amount: 300.00
},
{
  OrderID: 2,
  CustomerName: 'Microsoft',
  ShipperCity: 'Los Angeles, CA, USA',
}

```
When the `DataGrid` starts to render the second row it will throw an error because is missing some information, my suggestion is to allow the user to not set a value in the response if it isn't needed

**Comment by geoperez** [comment]
This ticket should be resolved into Tubular Common
