### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ArCiGo** [unosquare/tubular-react#171]
* Add code on the samples.
* Change some CSS styles

**Comment by geoperez** [comment]
Status?

**Comment by ArCiGo** [comment]
In progress. I didn't have time to update the doc.

**Comment by ArCiGo** [comment]
I was checking the current status of the project. Will Ana or Israel add a new functionality?

**Comment by geoperez** [comment]
Nop, just bug fixing.

**Comment by geoperez** [comment]
Closing
