### ISSUE TITLE
Fix Coverage

### ISSUE THREAD

**Issue by Israel-94** [unosquare/tubular-react#183]
**Describe the bug**
Coverage is failing

**Comment by geoperez** [comment]
Also, ignore Mocks folder

**Comment by geoperez** [comment]
You need to fix the tests first.

**Comment by geoperez** [comment]
I moved the coverage reporter from Coveralls to [Codacy](https://app.codacy.com/project/UnosquareLabs/tubular-react/dashboard). The required changes are in place at Travis.
