### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by ArCiGoUnoSquare** [unosquare/tubular-react#19]
* Add a footer to grid component

**Comment by geoperez** [comment]
@kadosh I don't like current implementation. The footer should not be part of the main component markup. You may add a [TableFooter](https://material-ui-next.com/api/table-footer/) connected to the Grid component.

**Comment by ArCiGoUnoSquare** [comment]
Let me correct it, @geoperez

**Comment by kadosh** [comment]
Let's be clear on this one. Table Footer is meant to be an optional element on the grid, but it has nothing to do with pagination, that's another story. So, I think we should provide a way to enable just a table footer, but take pagination out of the equation.
