### ISSUE TITLE
Logs - Application logs filters - Filter popup locks all the page and there is no tooltip

### ISSUE THREAD

**Issue by JavierMD** [unosquare/tubular-react#229]
**Describe the bug**
When I open a filter popup all the page gets locked and is not letting me escape with the keyboard or clicking anywhere else to cancel I'm forced to clear or apply again the filter

**To Reproduce**
1. Login as admin
2. Click on 'Logs' or go to https://accesscore.azurewebsites.net/#/Logs
3. Select the filter
4. Page gets locked until click CLEAR or APPLY

**Expected behavior**
The filter popup should be easy to exit

**Screenshots**
![image](https://user-images.githubusercontent.com/40582055/46166421-c43c5900-c258-11e8-9d66-1b8c6642023c.png)
https://i.imgur.com/Kg0Uk6F.gifv

**Comment by AlexisDragneel** [comment]
the last issue is more related with to the implementation of access core dialogs, I need the direction of the vpn to test accescore @geoperez could you send me the info necessary for access to the unosquare vpn?

**Comment by AnyxLeo** [comment]
@AlexisDragneel It is a Generic issue. doesn't depend on the application. You can see it on tubular-react itself.

**Comment by AnyxLeo** [comment]
The issue was resolved.
