### ISSUE TITLE
Pagination: Last page number is not displayed

### ISSUE THREAD

**Issue by JavierMD** [unosquare/tubular-react#231]
**Describe the bug**
When paginating and the user goes to the last page, is not clear if he's in the penultimate or last

**To Reproduce**
https://i.imgur.com/vsihnFM.gifv

**Expected behavior**
The page number should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/40582055/46224581-607b6400-c31c-11e8-880a-6573814fd755.png)

**Desktop (please complete the following information):**
- OS: Windows 10 pro
- Browser: Google Chrome
- VersionVersion 64.0.3282.140 (Official Build) (64-bit)

**Comment by JavierMD** [comment]
The last page is not displayed yet

**Comment by geoperez** [comment]
@AlexisDragneel the first and second page are showing the same data. Please fix.
