### ISSUE TITLE
Document the way that you can add functionality buttons to the grid

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#244]
**Is your feature request related to a problem? Please describe.**
There is no documentation that explained how we can add buttons that helps us to extend grid functionality.

**Describe the solution you'd like**
Upgrade the documentation with an explanation and examples of adding buttons.

**Additional context**
The image below shows an example of a button added.
![image](https://user-images.githubusercontent.com/26309079/47231106-9ea2fb00-d391-11e8-9802-68f7902763af.png)

**Comment by xquetzalcoatl** [comment]
Estimated time 2 hrs

**Comment by xquetzalcoatl** [comment]
Modify Readme file
