### ISSUE TITLE
Records not found

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#247]
**Is your feature request related to a problem? Please describe.**
When the grid is loading immediately appears the icon and the legend "records not found" it must appear after the grid loads and only in the case that there weren't rows to show.

**Describe the solution you'd like**
The icon and legend "Records not found"must appear after the grid loads and only in the case that there weren't rows to show.

**Additional context**
![image](https://user-images.githubusercontent.com/26309079/47518565-f2f62100-d850-11e8-80ee-e21c9ad41ec0.png)

![image](https://user-images.githubusercontent.com/26309079/47518587-ff7a7980-d850-11e8-8a29-a11671f58370.png)

**Comment by AlexisDragneel** [comment]
estimated time 4 hours.
