### ISSUE TITLE
Upgrade Material-UI Typography 

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#262]
**Is your feature request related to a problem? Please describe.**
The new release of material-ui changed the variants of the typography.

**Describe the solution you'd like**
Change the variant to their equivalent in Material-UI last release version.

**Additional context**
https://material-ui.com/style/typography/#migration-to-typography-v2

**Comment by geoperez** [comment]
Already fixed!

**Comment by Solenasth** [comment]
estimated difficulty: 2 given my inexperience with the code structure. 
ETA: less than 8 hours. (most of that time will be spent understanding the code)
