### ISSUE TITLE
Links' styles

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#272]
**Is your feature request related to a problem? Please describe.**
The color of the links can be changed. The links only accept the team that was used on Tubular-React as principal.

**Describe the solution you'd like**
The page links of the paginator must take the color from the application's general theme

**Comment by aetejeida** [comment]
For this changes, i think it's wanna take 5 hours because i do not know the project and I have time to see how it is structured and how it works internally in the code.

**Comment by Solenasth** [comment]
taking over this ticket as angel is focusing on other issues, Difficulty and time estimation remains the same, for the same reason, inexperience with the code.

**Comment by Solenasth** [comment]
after several tests we have concluded that this issue is not on tubular react, it belongs in mailerIO, closing this ticket as discussed previously with @AnyxLeo
