### ISSUE TITLE
Responsive grid

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#315]
**Is your feature request related to a problem? Please describe.**
If you visualize the grid in a mobile device, the grid shrink and the content isn't readable.

**Describe the solution you'd like**
The grid should be responsive. 

**Additional context**
![2019-06-03_10-37-33](https://user-images.githubusercontent.com/26309079/58814612-aabf8e00-85eb-11e9-8e16-e71b665dcafc.gif)

**Comment by kadosh** [comment]
Can we close this one? I can see a commit to master with a name that matches with this ticket. cc @AnyxLeo

**Comment by AnyxLeo** [comment]
Yes,  there was a commit that tried to solve the problem, the thing is that we redefine the approach to obtain the grid resizable.
When the resolution change to mobile resolution the grid should be a grid list instead.

I opened an issue with the new resolution.

https://github.com/unosquare/tubular-react/issues/321
