### ISSUE TITLE
Remove DataGridWithRemoteDataSource

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular-react#322]
**Is your feature request related to a problem? Please describe.**
With the DataGridWithRemoteDataSource component, tubular is hiding useful features on the toolbar and also, it is implementing a modal feature that is very limited and bug-prone when it comes to state on parent components.

**Describe the solution you'd like**
Tubular should care about the rendering of the grid and the bare bones features for it: paging, sorting, filtering. But when it comes to adding/editing a row, that should be delegated to the specific implementation. DataGridWithRemoteDataSource  was intended to provide a way to enable modal dialogs, but it is producing more problems than the ones it actually fixes.

**Comment by geoperez** [comment]
Done!
