### ISSUE TITLE
Add NextJS to improve Search Engine ranking

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/tubular-react#337]
In order to improve the Search Engine ranking of the docs, it would be great if we add NextJS to display more content to the "crawlers"

**Comment by MarcoLPR** [comment]
EOD: I have some trouble implementing Next JS, because all the styles that I used on the docs doesn't work anymore, I have to check the server side CSS rendering: https://material-ui.com/guides/server-rendering/

Also, It doesn't detect my _app or _document files to create a template for the components.

**Comment by geoperez** [comment]
Please keep this issue with the lowest priority.

**Comment by MarcoLPR** [comment]
Ok

**Comment by geoperez** [comment]
Can we test https://reactjs.org/docs/react-dom-server.html?

**Comment by kadosh** [comment]
I think this is not relevant anymore. Can you please confirm @geoperez @MarcoLPR

**Comment by geoperez** [comment]
Yeah, let's focus on static we sites with codesandbox
