### ISSUE TITLE
Paginator not working on multiple clicks

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/tubular-react#338]
If you click several times to go to next or prev page, the grid changes and make a lot of calls.
Both in basic and advance pagination.

1. Go to a grid and quickly click on the paginator buttons. 

Expected result:
Smoothly change into the last clicked page.

Actual result:
Loop between pages in the grid

![PaginationError](https://user-images.githubusercontent.com/25437790/61903513-4c77a300-aeea-11e9-9f6e-f6bab7c25721.gif)

**Comment by geoperez** [comment]
You can check the previous code of Tubular for AngularJS. The previous grid blocks HTTP request until one is resolved, you can also block the UI when the request is pending.

**Comment by MarcoLPR** [comment]
EOD note:
I'm looking for the code that Geo suggested to avoid this behavior. I still can't identify it, tomorrow I'm going to keep looking and fix this bug.

**Comment by geoperez** [comment]
You can just try to figure out what I am suggesting.

**Comment by MarcoLPR** [comment]
EOD:
I added a debounce to avoid multiple requests, but talking with @kadosh , he suggested to do a little refactor in the paginator to switch between complexity and block the UI when there is an operation running like sorting or searching. I have all to do it, so, it would be easy.

**Comment by kadosh** [comment]
Closing this one, #345 fixed this.
