### ISSUE TITLE
Refresh Grid

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#382]
**Is your feature request related to a problem? Please describe.**
When we use a modal to add or edit beside a Datagrid, the expected behavior is that when the action (add/ edit) is performed successfully the Datagridrefreshes and shows the new changes, but the Datagrid doesn't provide a method to do so.

**Describe the solution you'd like**
I would like the Datagrid exposes a boolean property that indicates to the Grid when refreshes itself.

**Additional context**
A possibility could be that in the **useDataGrid Hook** there is a function called **_processRequest_** which make a new request each time that is called and there is a **_useEffect_** which call the function every time that these properties change _( getColumns, getPage, getSearchText, getItemsPerPage)._  
We can add here our **refresh** property.

**Comment by geoperez** [comment]
@AnyxLeo you can check the new version.

@MarcoLPR you too!
