### ISSUE TITLE
Custom bodyrender implementing onClickRow

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#395]
**Is your feature request related to a problem? Please describe.**
When the custom body render is used, there is no way to set the action of onRowClick, the signature of the body render doesn't allow the use of a proxyClick and if the onRowClick is set on the grid or gridtable props it doesn't work.

**Describe the solution you'd like**
A way to set onClickRow on the definition of the bodyrender.

**Additional context**
![image](https://user-images.githubusercontent.com/26309079/63445059-5e6f3780-c3fd-11e9-8ce6-04d117123480.png)

**Comment by kadosh** [comment]
Fixed at #396

**Comment by geoperez** [comment]
@AnyxLeo is this ready to close?

**Comment by AnyxLeo** [comment]
@geoperez 
yes it is ready to close
