### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#425]
**Describe the bug**
When I am trying to select an operator in the filter pop up, the application crashes

**To Reproduce**
1. Go to a grid's column with filter
2. Click on the filter icon
3.  Select an operator

**Expected behavior**
I should be able to select the filter type

**Screenshots**
![image](https://user-images.githubusercontent.com/26309079/64927886-237eda80-d7d6-11e9-8fcc-d0063b1e981f.png)

![image](https://user-images.githubusercontent.com/26309079/64928447-2aa9e680-d7de-11e9-9810-18647a8e017f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 76.0.3809.132

**Additional context**
![VdZUU9SIdo](https://user-images.githubusercontent.com/26309079/64927856-d7339a80-d7d5-11e9-9ada-135098ee7514.gif)

**Comment by geoperez** [comment]
Somehow the ColumnModel class is lost and an anonymous object is holding the column data without the public methods. I'll revert Tubular-Common to contains those methods as public static.

**Comment by geoperez** [comment]
Done! You can check the new version!
