### ISSUE TITLE
Grid with local data

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#433]
**Describe the bug**
I am giving an empty array as the initial data source to the grid, the first time that I add a row the page counter shows a negative number and the grid shows nothing and in the paginator is the number one. Until I click the advance button on the paginator, the grid shows the added row

**Expected behavior**
It should show the correct page and the correct pager counts from the beginning.

**Additional context**
![2019-09-23_15-58-03](https://user-images.githubusercontent.com/26309079/65463254-1f2d6f80-de1d-11e9-9d7e-e32861c87a54.gif)

**Comment by kadosh** [comment]
@AnyxLeo  can we close this one?

**Comment by AnyxLeo** [comment]
Yes @kadosh it already works
