### ISSUE TITLE
Reduce bundle size by importing specific @material-ui modules

### ISSUE THREAD

**Issue by stikut** [unosquare/tubular-react#502]
**Is your feature request related to a problem? Please describe.**
Currently, the library adds ~100KB to the total production bundle size (Gzipped) even though I already have material-UI in my project. @material-ui/core is being fully imported.

**Describe the solution you'd like**
Avoid importing the whole @material-io/core - use specific imports instead, as described here:
https://material-ui.com/guides/minimizing-bundle-size/

e.g.
import List from '@material-ui/core/List'

**Comment by stikut** [comment]
OK, found the culprit - it's actually uno-material-ui

**Comment by geoperez** [comment]
Ok, we are going to check uno-material-ui then.
