### ISSUE TITLE
Data Grid header space

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular-react#518]
**Describe the bug**
DataGrid header contains an ugly space at the top. It might be due to the LinearProgress shown when loading is happening.

**To Reproduce**
Look at the docs or the attached screenshot 

**Expected behavior**
The header of the grid should not contain that space.

**Screenshots**
![image](https://user-images.githubusercontent.com/399019/70167964-7b1e3b00-168d-11ea-9585-afa5e805fc65.png)

**Comment by geoperez** [comment]
@kadosh can you review this issue?

**Comment by kadosh** [comment]
This is no longer valid. We could probably need to improve the Header style but it will be handled in a separate issue.
