### ISSUE TITLE
Can't import anything from tubular-react

### ISSUE THREAD

**Issue by puruaptus** [unosquare/tubular-react#570]
**Describe the bug**
The module `tubular-react` can't be found when trying to import.

**To Reproduce**
1. Create a new react-app
2. Install the module using ```npm i tubular-react```
3. Try importing anything from the package 
e.g. ``` import { DataGrid } from "tubular-react"```

**Expected behavior**
No errors.

**Screenshots**
![Annotation 2020-01-06 130935](https://user-images.githubusercontent.com/47772502/71803187-12f4b780-3086-11ea-9c08-60f351959509.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (1903)
 - Browser: Chrome
 - Version: 79

**Additional context**
This error shouldn't exist.

**Comment by geoperez** [comment]
Hello, can you try with the v4.0.4? There was an error in the publishing process.
