### ISSUE TITLE
CSS Overrides

### ISSUE THREAD

**Issue by ziggyjosh16** [unosquare/tubular-react#578]
**Is your feature request related to a problem? Please describe.**
This component is great but it affects the CSS of my parent components.
**Describe the solution you'd like**
Update the documentation of to include CSS overrides

**Comment by kadosh** [comment]
Hi @ziggyjosh16,

Can you please provide more information about the issue you're seeing? Like, how you're integrating tubular-react? which version of Material-UI you're using and so on? 

Thanks in advance.

**Comment by geoperez** [comment]
Status?

**Comment by ziggyjosh16** [comment]
Apologies,

I ran into a hardware issue with my machine and it is being warranty
repaired so I can't provide this information in detail just yet.

I started by using this component by dropping it directly into one of my
layout components which I also imported. When I do this or affects the look
of my parent components including the router. I'm assuming it is because of
CSS, but I can't override anything to find which style is causing the issue.

I can provide code and screenshots later.

Josh

**Comment by kadosh** [comment]
I just tried again doing something like that on a new sandbox and it is working fine as you can see at: https://codesandbox.io/s/material-ui-dark-theme-b9r3z

So, please let me know how I can help you. You can try by upgrading your mui/deps version.

**Comment by ziggyjosh16** [comment]
Does this example you made in Sandbox work with the DataGrid Component?

**Comment by kadosh** [comment]
@ziggyjosh16, yeah, I created that codesanbox with a simple DataGrid component so you can see the result.

**Comment by geoperez** [comment]
Related to #665

**Comment by geoperez** [comment]
@ziggyjosh16 did you get a chance to see the codesanbox?

**Comment by ziggyjosh16** [comment]
Yes. My issue is similiar to #655 I fixed it by updating my version.
