### ISSUE TITLE
Date Time columns' filter is crashing

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular-react#580]
**Describe the bug**
Latest release is crashing whenever you try to filter by a column which is type is DateTime

**To Reproduce**
1. Go to any grid with datetime columns
2. Try to open the filter popup
3. See error

**Additional context**
Please keep in mind that we have done a lot of changes. And please consider adding at least one unit test so that we can ensure that we won't break this in the future.

**Comment by fr3sh** [comment]
The same here ;(

**Comment by kadosh** [comment]
hi @fr3sh,

Thanks for using tubular-react. We have fixed this issue, please use version 4.1.3 or you can take a quick look into it at https://codesandbox.io/s/bold-silence-k8vwk. Please let me know if you have any further issues.
