### ISSUE TITLE
mobileBreakpointWidth isn't working

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-react#585]
https://codesandbox.io/s/remotedatagrid-mobilebreakpointwidthwidth-example-lumcz

![2020-01-16_10-41-54](https://user-images.githubusercontent.com/26309079/72561317-91afd880-386e-11ea-9273-965785c87a01.gif)

![image](https://user-images.githubusercontent.com/26309079/72561391-bb68ff80-386e-11ea-975a-a7f76883ad99.png)

**Comment by kadosh** [comment]
I already checked the error and it is related to a missing theme provider on the example app. So, you only need to provide a main theme for your DataGrid Component.

For instance, check https://codesandbox.io/s/remotedatagrid-mobilebreakpointwidthwidth-example-d0cro

@AnyxLeo can you check it and let me know if everything is fine?
