### ISSUE TITLE
filter blocked

### ISSUE THREAD

**Issue by fr3sh** [unosquare/tubular-react#603]
When you try to use filter and try to type something after you choose the operator the value is still blocked you can't type anything. See codesandbox below 

https://codesandbox.io/s/ecstatic-rain-6oyqy?from-embed

**Comment by kadosh** [comment]
hi @fr3sh,

Thanks for using tubular-react. We have fixed this issue, please use version 4.1.3 or you can take a quick look into it at https://codesandbox.io/s/bold-silence-k8vwk. Please let me know if you have any further issues.

**Comment by fr3sh** [comment]
Thank you! 
Can I have few more qestions:
1. Do you support localizations?
2. How to add custom button icon to the rows to handle data?
3. Is it posible to filter column when you typing on filter column not by clicking apply

**Comment by kadosh** [comment]
1. No. tubular-react doesn't support localizations, but you can always 
2. Yes, you can specify the way you want to render your rows.

You can define a custom row like:
```tsx
const CustomTbRow: React.FunctionComponent<TbRowProps> = ({ row, onRowClick }: TbRowProps) => (
    <TableRow hover={true} key={row.OrderID} onClick={onRowClick}>
        <TableCell padding="default">{row.OrderID} </TableCell>
        <TableCell padding="default">{row.CustomerName} </TableCell>
        <TableCell padding="default">{formatDate(row.ShippedDate, 'M/d/yyyy h:mm a')}</TableCell>
        <TableCell padding="default">{row.ShipperCity}</TableCell>
        <TableCell padding="default" align={'right'}>
            {row.Amount || 0}
        </TableCell>
        <TableCell padding="default">{row.IsShipped ? <CheckBox /> : <CheckBoxOutlineBlank />}</TableCell>
    </TableRow>
);
```
And then you can use it with DataGridTable component.

```tsx
const tbTableInstance = useTbTable(sampleColumns, localData);

<DataGridTable
    tbTableInstance={tbTableInstance}
    rowComponent={CustomTbRow}
/>
```

Please take a look at the example found at: https://github.com/unosquare/tubular-react/blob/master/sample/src/CustomLayoutDataGrid.tsx. You can take control on anything.

In fact, you can implement your own table with localization the way you want.

3. At this moment No. The filter event will be executed when clicking on apply. But you are welcome to create a PR to support that.

**Comment by kadosh** [comment]
Hi @fr3sh,

We have added support for localization. You can take a look at: https://github.com/unosquare/tubular-react/blob/master/test/LanguageService.spec.ts to understand how you can add your own localization file.

**Comment by kadosh** [comment]
Closing this one because original issue has been resolved.
