### ISSUE TITLE
Can not render nested objects

### ISSUE THREAD

**Issue by carlosirazabal** [unosquare/tubular-react#614]
Hi There, I'm using ColumnModel class according the documentation to render my data, but when I try to render a nested data it does not work.

![Captura de Pantalla 2020-02-03 a la(s) 01 30 44](https://user-images.githubusercontent.com/32577691/73630814-324f1800-4625-11ea-8f68-cbf45d43e860.png)
<img width="826" alt="Captura de Pantalla 2020-02-03 a la(s) 01 31 35" src="https://user-images.githubusercontent.com/32577691/73630820-367b3580-4625-11ea-9323-bb691a445a53.png">

Thanks in advance.

OS. MACBook Pro Catalina
Browser: Chrome last version

**Comment by kadosh** [comment]
Hi @carlosirazabal ,

Thanks for using tubular-react. Regarding the issue you're reporting, we have not enabled tubular-react to work with nested objects. For those cases, I would recommend to make a flat datasource and avoid nested objects as much as possible.
