### ISSUE TITLE
Is it able to select a row?

### ISSUE THREAD

**Issue by jaychang0917** [unosquare/tubular-react#622]
Great library, I am wondering if the library supports selecting a row like https://material-ui.com/components/tables/#sorting-amp-selecting?

**Comment by kadosh** [comment]
Hi @jaychang0917,
Thanks for your interests on tubular-react. We don't currently support selection functionality. But we will think about it and see how to implement it. Or you're always welcome to submit a PR with a proposal.

**Comment by kadosh** [comment]
After reviewing the Material Design for DataTables, we have decided to adopt the specification regarding row selection.

![image](https://user-images.githubusercontent.com/399019/74445234-ac5c7980-4e3b-11ea-87ac-be7fb3cd5323.png)

![image](https://user-images.githubusercontent.com/399019/74445159-8cc55100-4e3b-11ea-8616-a444303874de.png)

**Comment by geoperez** [comment]
Hi @AlexisDragneel , are you working on this issue?

**Comment by geoperez** [comment]
Status?

**Comment by geoperez** [comment]
Hi @kadosh, are you working on this issue?

**Comment by kadosh** [comment]
Hi @geoperez,
I'm not working actively on this one, but it will be included in the next releases.

**Comment by geoperez** [comment]
Cool, thank you!

**Comment by kadosh** [comment]
FYI, this feature is in dev process. You can follow the progress here: #736
