### ISSUE TITLE
Table header is off a column when using detailComponent

### ISSUE THREAD

**Issue by atjeff** [unosquare/tubular-react#660]
**Describe the bug**
When passing a detail component, an extra column is added to each row for the plus icon (that triggers the detail component) but a blank table header column isn't added to offset this add. This makes the entire table look bad.

**To Reproduce**
https://codesandbox.io/embed/tubular-react-detailcomponent-yusvc?fontsize=14&hidenavigation=1&theme=dark&previewwindow=editor,browser

**Expected behavior**
An extra table header should be added to the table.

**Comment by atjeff** [comment]
Seems like a problem here https://github.com/unosquare/tubular-react/blob/master/src/DataGrid/GridHeader.tsx#L34

**Comment by kadosh** [comment]
Thanks for your report @atjeff ,

We'll be checking it ASAP.

**Comment by atjeff** [comment]
Thanks guys!
