### ISSUE TITLE
Opening the filter dialog on any date field throws react errors and doesn't update on input

### ISSUE THREAD

**Issue by atjeff** [unosquare/tubular-react#690]
**Describe the bug**
Opening the filter dialog on any date field throws react errors and doesn't update on input. Error is thrown in all browsers, in firefox I am unable to interact with the Label_Value ui. In general the Label_Value ui is really hard to use with any date, datetime, etc.

**To Reproduce**
1. Open https://codesandbox.io/s/tubular-react-datagrid-bzndx
2. Open javascript console
3. Click on the filter icon on Shipped Date
4. Note errors in console
5. Note that clicking any dates on any of the filter options is broken.

**Expected behavior**
No errors in console, clicking / typing inputs reflects in UI.

**Screenshots**

**Additional context**

**Comment by kadosh** [comment]
Hi @atjeff ,
The UI has changed completely. I still need to update our code sandboxes, but if you want to, you can take a look at the latest version and let me know if you still have problems.

**Comment by nickpalmer** [comment]
This is fixed in #800
