### ISSUE TITLE
_tubularCommon.ColumnModel is not a constructor

### ISSUE THREAD

**Issue by robbiedh** [unosquare/tubular-react#709]
hello , i tried example of tubular-react but not working properly ,
,i get some error like this 

> _tubularCommon.ColumnModel is not a constructor'

 i don't know what happened , anyone could help me please ?
on below detail my code

> import React from "react";
> import "./styles.css";
> import { DataGrid } from "tubular-react";
> import { ColumnModel } from "tubular-common";
> 
> export default class App extends React.Component {
>   render() {
>     const columns = [
>       new ColumnModel("OrderID"),
>       new ColumnModel("CustomerName"),
>       new ColumnModel("ShipperCity")
>     ];
> 
>     return (
>       <div className="App">
>         <DataGrid
>           columns={columns}
>           dataSource={"https://tubular.azurewebsites.net/api/orders/paged"}
>           gridName="Grid"
>         />
>       </div>
>     );
>   }
> }

package.json

> {
>   "name": "react",
>   "version": "1.0.0",
>   "description": "React example starter project",
>   "keywords": [
>     "react",
>     "starter"
>   ],
>   "main": "src/index.js",
>   "dependencies": {
>     "react": "16.12.0",
>     "react-dom": "16.12.0",
>     "react-scripts": "3.0.1",
>     "react-tubular": "0.0.2",
>     "tubular-common": "4.0.3",
>     "tubular-react": "4.1.23"
>   },
>   "devDependencies": {
>     "typescript": "3.3.3"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test --env=jsdom",
>     "eject": "react-scripts eject"
>   },
>   "browserslist": [
>     ">0.2%",
>     "not dead",
>     "not ie <= 11",
>     "not op_mini all"
>   ]
> }

**Comment by kadosh** [comment]
Hi @robbiedh,

We have removed ColumnModel class. It is now an interface. You can simply change your code into:

```tsx
const columns = [
    createColumn("OrderID"),
    createColumn("CustomerName"),
    createColumn("ShipperCity")
];
```
And just import that function from the tubular-common package. Let me know if that works for you.

**Comment by robbiedh** [comment]
thanks @kadosh
