### ISSUE TITLE
Export CSV doesn't work on IE11

### ISSUE THREAD

**Issue by chetan552** [unosquare/tubular-react#772]
**Is your feature request related to a problem? Please describe.**
Export CSV doesn't work on IE11. 

**Describe the solution you'd like**
This issue is fixed with a fix in tubular-react-common 2.0.7. https://github.com/unosquare/tubular-react-common/issues/141
The current version of tubular-react uses 2.0.4 version of tubular-react-common.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by kadosh** [comment]
Hi @chetan552 ,
Can you confirm that you're fine with the update we did on dependencies? Please, let me know if you have further problems
