### ISSUE TITLE
Review github action for forks

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular-react#811]
Can we take a look at our workflow and see if we can run successfully our pipeline on forks?

**Comment by geoperez** [comment]
I'll change the workflow with the new Super Linter (https://github.com/github/super-linter)

**Comment by geoperez** [comment]
Still checking super linter, this is failing :(

**Comment by nickpalmer** [comment]
Yes please. I tried to get it to work in #830 but that PR is still failing, though `yarn lint` passes on the branch.
