### ISSUE TITLE
Column filtering doesn't work in first example

### ISSUE THREAD

**Issue by jenkin** [unosquare/tubular-react#813]
**Describe the bug**
In [this example](https://codesandbox.io/s/tubular-react-template-gyjo8) listed in [README](https://github.com/unosquare/tubular-react#example) some columns are defined with `filtering: true` but no filter icon is shown.

**To Reproduce**
1. Go to https://codesandbox.io/s/tubular-react-template-gyjo8
2. Wait for loading
4. No filter is shown

**Expected behavior**
With `filtering: true` no filter is shown. BUT with `filterable: true` (file `src/Main.jsx`) it works! BUT if you upgrade `tubular-react` from v4.1.25 to v4.1.35 (file `package.json`), neither the first nor the second option works. The issue seems to occur from v4.1.27 included.

**Desktop (please complete the following information):**
CodeSandbox with Chromium Version 80.0.3987.162 (Build) built on Debian 10.3, running on Debian 10.4 (a 64 bit)

**Comment by kadosh** [comment]
Hi @jenkin,

We're in the middle of several changes. One of them was to remove filter features from the column component. The latest version contains filter features inside a drawer. Give me a few to provide a codesandbox.

**Comment by jenkin** [comment]
Ok, for now I stick to v4.1.26 and wait for updates, thanks!

**Comment by kadosh** [comment]
Hey @jenkin, please check the following codesandbox:
https://codesandbox.io/s/tubular-react-template-n042f

As you can see:
1) The property for the column is ```filterable```
2) In order to filter a column, there's a new toolbar button to open column filters

![image](https://user-images.githubusercontent.com/399019/85154869-a4fc1100-b21d-11ea-8ef4-348e5d1051ee.png)

**Comment by kadosh** [comment]
I'll close this one since there is not really an issue and we're working on updating the Readme to avoid any further misunderstanding.

This is the ticket for that effort: https://github.com/unosquare/tubular-react/issues/814
