### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular-react#829]
There are a couple of issues with the current README:

1. Codesandbox link is out-of-date. Click on that link and see that the codesandbox is using a very old version of tubular. Please update that codesandbox,
![image](https://user-images.githubusercontent.com/399019/85820374-b83a3f80-b73b-11ea-861f-f05a6a38a87a.png)

2. GIF on DataGrid sample is showing an out-of-date demo. Please provide a 
![image](https://user-images.githubusercontent.com/399019/85820531-094a3380-b73c-11ea-91e3-05b52c0bf5d8.png)

A good review on the file is needed.

**Comment by geoperez** [comment]
Can you fix?

**Comment by geoperez** [comment]
😿
