### ISSUE TITLE
Modify website to display samples and documentation.

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/tubular-react#83]

**Comment by geoperez** [comment]
Warning: Invalid DOM property `charset`. Did you mean `charSet`?
    in meta (at MetaData.js:11)
    in head
    in Head
    in html
    in Document
  exporting path: /Sample
  exporting path: /Documentation/ColumnModel
Warning: Failed prop type: Invalid prop `hover` of type `string` supplied to `TableRow`, expected `boolean`.
    in TableRow
    in WithStyles(TableRow) (at ColumnModelTable.js:19)
    in tbody
    in TableBody (at ColumnModelTable.js:18)
    in table
    in Table
    in WithStyles(Table) (at ColumnModelTable.js:7)
    in ColumnModelTable (at ColumnModel.js:39)
    in div
    in Paper
    in WithStyles(Paper) (at ColumnModel.js:36)
    in div
    in Grid
    in GridWrapper
    in WithStyles(GridWrapper) (at ColumnModel.js:35)
    in div
    in Grid
    in GridWrapper
    in WithStyles(GridWrapper) (at ColumnModel.js:29)
    in div (at ColumnModel.js:26)
    in ColumnModel
    in WithStyles(ColumnModel)
    in AppContainer
    in Container
    in App

**Comment by geoperez** [comment]
Also, include the build process when you run the doc command.
