### ISSUE TITLE
Ability to have Multiple Filters on a Field

### ISSUE THREAD

**Issue by shrey-g** [unosquare/tubular-react#889]
**In our application we want to have multiple filters on every field**
We have a requirement to add multiple filters on field, so when I add a filter it shows up as a tag with cross icon 

**Describe the solution you'd like**
Custom tag component  that shows up when a filter is active 
Cross icon to remove that filter

**Describe alternatives you've considered**
None

**Additional context**
We can toggle this multi-filter behaviour with a prop

**Comment by shrey-g** [comment]
@geoperez 
We need it urgently 
I will be working on a fix for the same in a fork
Can I submit a PR for the same after it's completed?

**Comment by geoperez** [comment]
Hey, are you using a local data source or remote?

@kadosh do you have any comments?

**Comment by kadosh** [comment]
We don't support multiple filters per field. Our implementation for Local/Remote data source is totally relying on the fact that a single filter exists per column.

Filters functionality has been removed from the column and now it is shown as a tag at the top of the grid.

**Comment by shrey-g** [comment]
@kadosh @geoperez 
Is there any way to do that or some other library that we can use ?
