### ISSUE TITLE
DetailComponent not compatible with onRowClick & rowSelectionEnabled?

### ISSUE THREAD

**Issue by Spinningbull** [unosquare/tubular-react#923]
**Describe the bug**
I have an existing table the lists records and leverages onRowClick to pop a dialog to edit the record, and uses rowSelectionEnabled to delete records.  

Now, I'm trying to add a detail component that lists related records (actually in another data table).

However, when I add the DetailComponent, the onRowClick is never called, and the selection column is never added.   

**To Reproduce**
Create a DataTable with onRowClick - test to make sure it works.
Add a DetailComponent - try to click on a row

**Expected behavior**
All three features work together.

- Detail component allows user to expand row,
- user can click on row (collapsed or expanded) to fire onRowClick event
- selection boxes appear between detail expansion icon and rest of row

**Screenshots**
![image](https://user-images.githubusercontent.com/16505631/92022332-f5104d00-ed0f-11ea-86ef-6dae832e8b96.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Spinningbull** [comment]
Is there a way to add components to each row?  Without taking over rendering of the whole row?  This would allow me to solve this problem...

**Comment by bmitchinson** [comment]
Holding out on whether or not to use this library depending on this issue, don't think it should be made stale just yet.

**Comment by geoperez** [comment]
@kadosh  ??

**Comment by Spinningbull** [comment]
Thanks @bmitchinson I was going to reply something similar.  I've been looking at alternatives because of this issue.  Would love to see it fixed.

**Comment by krysia-w** [comment]
Still no news on this? 
It's a hige bug IMO, as all 3 options are provided out of the box. It should be as simple as not firing the rowClick when user selected the row via the "selection box" or expanded the details, or even adding the "event" to the onRowClick so we can distinguish the action ourselves . C'mon.

**Comment by krysia-w** [comment]
Answering myself, but in case anyone needs it here's a working workaround for the select+onclick scenario (can probably be easily adapted to the details as well)
`

    import { DataGrid, TbRow } from 'tubular-react';

    ....

    const customRow = ({
        row,
        rowIndex,
        columns,
        rowSelectionEnabled,
        selection,
    }) => {
        const onRowClick = (e) => {
        const { target } = e;

        if (target.type === 'checkbox') {
            /** the selection checkbox has been clicked, do nothing */
            return;
        }
        /** the code below is only executed if the click was not in the checkbox */
        /**
        * todo: actions on click, has acceess to `row`
        */
        };

        /** use the tubular row component so it handles the selection */
        return (
        <TbRow
            row={row}
            key={rowIndex}
            rowIndex={rowIndex}
            columns={columns}
            onRowClick={onRowClick}
            rowSelectionEnabled={rowSelectionEnabled}
            selection={selection}
        ></TbRow>
        );
        
        ...

        <DataGrid
            ...
            rowComponent={customRow}
            // NO onclick method here! onRowClick={onRowClick}
            rowSelectionEnabled={true}
        ></DataGrid>
`

**Comment by kadosh** [comment]
Sorry guys, I've been very busy. Let me review this.

**Comment by kadosh** [comment]
@krysia-w, @Spinningbull , @bmitchinson please take a look at #1032 and let me know your thoughts about it.

**Comment by Spinningbull** [comment]
@kadosh proposal looks good, eager to test it out.  Should I wait for merge?

**Comment by kadosh** [comment]
4.2.12 is out, you can give it a try
